all : part1 part2 part3 part4

part1: 
	gcc -Wall -o part1 part1.c

part2: 
	gcc -Wall -o part2 part2.c

part3: 
	gcc -Wall -o part3 part3.c

part4:
	gcc -Wall -o part4 part4.c

clean: 
	rm part1 part2 part3 part4
